#!/usr/bin/env php
<?php

$rootDir = __DIR__;

require $rootDir.'/bootstrap.php';
$config = include $rootDir.'/config/console.php';

unset($_ENV['DB_PASSWORD']);
unset($_SERVER['DB_PASSWORD']);

exit((new yii\console\Application($config))->run());
